/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.VersionControl;
import javax.swing.*;
import java.awt.*;
public class App {
    

    public static void main(String[] args) {
        EvaluatorWindow w = new EvaluatorWindow();
        
        JFrame frame = new JFrame("Expression Evaluator");
        frame.setLayout(new BoxLayout(frame.getContentPane(), BoxLayout.Y_AXIS)); 
        frame.setSize(500,100);
        frame.add(w.expressionText);
        frame.add(w.evaluateButton);
        frame.add(w.outputLabel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
}

